### ISSUE TITLE
Analog video out

### ISSUE THREAD

**Issue by owlnonymous** [va7deo/MegaSys1_A#1]
By default, the analog video out Refresh Rate is set to Native, which is incompatible with most PVMs. Setting Refresh Rate to NTSC help descramble the sync. Possibly set Refresh Rate to NTSC be default for improved compatibility out the gate?

**Comment by atrac17** [comment]
No, this would alter the native PCB refresh rate. You'd have to toggle and save. The intent is for it to boot like the PCB at launch.

**Comment by atrac17** [comment]
@owlnonymous also try adjusting the analog sync H/V-sync width adjust too, you may be able to fix sync roll that way. I tested on a few different lower end PVMs and commercial sets and achieved success depending on the display.

**Comment by atrac17** [comment]
Fixed with latest beta, mame timings are inaccurate. @owlnonymous give the new release a go without toggling to NTSC.

**Comment by owlnonymous** [comment]
Yes, the Native Refresh Rate now works with my PVM. Thanks
