### ISSUE TITLE
potential sync issues with vsync_adjust=1 and vsync_adust=2 on some devices with latest core 20230701

### ISSUE THREAD

**Issue by Videodr0me** [va7deo/MegaSys1_A#3]
I noticed that on my LG C9 i get no sync for these titles with vsync_adjust=1 or 2. I know that this might be a weird interaction between the LG C9 and the particulars of these arcade machines timing, but for a couple of reasons i suspect there might be an edge case with this cores timing or the misters vsync adjustment:

1) all cores, no matter how strange their refresh rates/resolutions/dynamic-switching,work with the LG9 and vsync_adjust=2. Even the notorious X68000  core works at nativ refresh rates and dynamic switching. All cores with <62hz work at all resolutionso, cores with refreshrates >62hz work with higher than hd resolutions e.g.: video_mode=1920,48,32,112,1200,3,6,32,154000
This makes this core the only one that does not sync and only works with vsync_adjust=0.

2) Even when the core is set to refresh rate NTSC it does not sync. This is what makes this really strange, as at approx 60hz syncing should be no problem. Even the resolution is not very unique as some other cores use the same. Also Scandoubler FX makes no difference - it will not sync no matter what the settings. Tried at all resolutions, mister.ini at default with only vsync_adjust = 2 and video_mode added. No VRR, no VRR settings in the ini.

3) There were some previous cases where vsync_adjust =2 would produce hdmi streams incompatible with some devices (to tight porches/vblanks/hblanks). Fortunately sorg could fix these in the past. Maybe this is one of those cases.

4) The previous version of the core worked MegaSys1_A_20230519.rbf perfectly with vsync_adjust = 2. The lastest does not. Tested with soldam.

So, this might not be a real bug in the core, but maybe the new timings of the latest core somehow trip the vsync adjustment algorithm. I know that vsync adjust = 2 is stretching the hdmi standard a lot, but maybe this can be easily fixed - maybe even with the old cores timings?

**Comment by atrac17** [comment]
This has already been addressed and fixed. Use the build provided here (https://github.com/va7deo/MegaSys1_A/issues/2) in the interim. It has nothing to do with the actual core timings. If the build provided fixes your issue please close.

Thanks!

**Comment by Videodr0me** [comment]
The developement version 20230706 (downloaded from a reply to issue#2) fixes this issue. Issue closed. Just curious, what exactly was the problem?

**Comment by atrac17** [comment]
Build tolerance, mister parts, etc... There is nothing wrong with sync in the core. Thankfully you understood that. All I did was recompile the source before I pushed changes to it yesterday.
