### ISSUE TITLE
Sync problem with latest core

### ISSUE THREAD

**Issue by ghost** [va7deo/MegaSys1_A#4]
The previous core (that run Saint Dragon) was working fine on my setup.
Vsync = 2
In game mode -> Native NTSC

latest core (that run Iga ninja)
All previous games black screen and sporadically blink the image (iga included)
vsync = 2
In game: any mode (60 or native, NTSC or PAL)

BTW, my LCD screen accept all frequencies from 47Hz to 75Hz. And all other cores are working fine with vsync = 2

**Comment by atrac17** [comment]
Fixed in https://github.com/va7deo/MegaSys1_A/commit/cfa8f6874d73d850472552631ca5f55db72309e4
